---
image: maven:latest
stages:
- build
- test
- deploy
sast:
  stage: test
include:
- remote: https://gitlab.com/gitlab-org/incubation-engineering/five-minute-production/library/-/raw/main/gcp/cloud-run.gitlab-ci.yml
- template: Security/SAST.gitlab-ci.yml

build:
  tags:
  - saas-linux-small-amd64
  stage: build
  script:
  - mvn clean package -DskipTests=true
  - ls

deploy-to-cloud-run:
  stage: deploy
  needs:
    - build